
Model_name: logistic_regression

Test_Train:
  test_size: 0.2
  Random_State: 0


Model_Params:
  C: 0.0005
  Random_State: 0

Pipeline:
  NUMERICAL_VARIABLES:
    - age
    - fare
  CATEGORICAL_VARIABLES: 
    - sex
    - cabin
    - embarked
    - title
  CABIN: 
    - cabin
  SALUTATION: 
    - name
  DROP:
    - name
    - ticket
    - boat
    - body
    - home.dest